<script lang="ts" setup></script>
<template>
  <div v-bind="$attrs">
    <div class="ldio-mm5gwljcryb">
      <div></div>
    </div>
  </div>
</template>
<style scoped>
  .ldio-mm5gwljcryb {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-mm5gwljcryb div {
    box-sizing: content-box;
    position: absolute;
    top: calc(50% - 12px);
    left: calc(50% - 12px);
    width: 24px;
    height: 24px;
    border: 4px solid #ddd;
    border-top-color: transparent;
    border-radius: 50%;
    animation: ldio-mm5gwljcryb 1s linear infinite;
  }

  @keyframes ldio-mm5gwljcryb {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }

  .loadingio-spinner-rolling-5kajof80q6w {
    width: 100%;
    height: 100%;
    display: inline-block;
    overflow: hidden;
    background: #ffffff;
  }

  /* generated by https://loading.io/ */
</style>
